### REGISTRO
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Yulian Cruz",
  "email": "yuliana@abc.com",
  "password": "123456"
}

### LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "yuliana@abc.com",
  "password": "123456"
}

### CREAR TAREA
POST http://localhost:3000/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ5dWxpYW5hQGFiYy5jb20iLCJpYXQiOjE3NjMwNzY3MDcsImV4cCI6MTc2MzA4MDMwN30.0XiG8F7N5DAkhhvHxRwv9BURtWioeDqPRg87K8ikeqM

{
  "title": "Actividad del dia",
  "description": "Aprender Backend"
}

### LISTAR TAREAS
GET http://localhost:3000/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ5dWxpYW5hQGFiYy5jb20iLCJpYXQiOjE3NjMwNzY3MDcsImV4cCI6MTc2MzA4MDMwN30.0XiG8F7N5DAkhhvHxRwv9BURtWioeDqPRg87K8ikeqM